dubbo:
  application:
    protocol: tri
  protocol:
    name: tri
    port: 20000
  registry:
    address: nacos://10.21.32.154:8848
spring:
  application:
    name: blc-provider
rocketmq:
  name-server: 10.21.32.221:9876
  producer:
    # 发送同一类消息的设置为同一个group，保证唯一
    group: testGroup
    # 发送消息超时时间，默认3000
    sendMessageTimeout: 10000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
    # 异步消息重试此处，默认2
    retryTimesWhenSendAsyncFailed: 2
    # 消息最大长度，默认1024 * 1024 * 4(默认4M)
    maxMessageSize: 4096
    # 压缩消息阈值，默认4k(1024 * 4)
    compressMessageBodyThreshold: 4096
    # 是否在内部发送失败时重试另一个broker，默认false
    retryNextServer: false
server:
  port: 8881
fisco:
  group: group0
  file-path: /fisco-config-dev.yml
  contract:
    admin: "2dbbf6b8894ed9b002445d7286124eb03291a574a23d5b3a92af654726e1ad92"
    address:
      poolData: "0x02c387f81f33bd252d5b6ad5952fcffa54edf5d7"
      poolLogic: "0xe117a3ad55a3c69adab5731fd21f0b1ee61a9667"
      userLogic: "0x7d9f2565ac99b30f2e3f26dd09c13aecbe08962f"
      userData: "0x92c9e53ccc9ff54413cac75a0952f8e2f907b977"
logging:
  level:
    com.topview.api.*: DEBUG